sudo: required
services: 
  - docker

before_install: 
  - docker build -t zfv2019/alexandria -f Dockerfile.dev .

script:
  - docker run -e CI=true zfv2019/alexandria npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "alexandria"
  env: "Alexandria-env"
  bucket_name: "elasticbeanstalk-us-east-1-536554314663"
  bucket_path: "alexandria"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"


  #   access_key_id:
  # secure: $AWS_ACCESS_KEY